/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Receitas;

import Telas.Tela_inicial;

/**
 *
 * @author user
 */
public class Tela_vegana extends javax.swing.JFrame {

    /**
     * Creates new form Tela_vegana
     */
    public Tela_vegana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VEGANO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 6, -1, 22));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("                 Wrap Vegano de Abacate e Vegetais\nCalorias: Aproximadamente 200 calorias por porção\nIngredientes:\n   1 tortilha de trigo integral (90 calorias)\n   1/2 abacate maduro amassado (120 calorias)\n   1/4 de pepino em fatias finas (5 calorias)\n   1/4 de cenoura ralada (10 calorias)\n   1/4 de pimentão vermelho em tiras (7 calorias)\n   Folhas de alface ou rúcula a gosto\n   Suco de 1/2 limão (2 calorias)\n   Sal e pimenta a gosto\n                      Modo de preparo\n Espalhe o abacate amassado sobre a tortilha de trigo integral.\n Adicione as fatias de pepino, a cenoura ralada, as tiras de pimentão\n e as folhas de alface ou rúcula.\n Tempere com suco de limão, sal e pimenta a gosto.\n Enrole o wrap, fechando as pontas.\n Corte ao meio e sirva.\n Essa receita de wrap vegano é rápida, leve e cheia de sabores frescos.\n É uma opção prática para refeições mais leves.");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 34, 580, 392));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/c.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 460));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("VOLTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/bb.jpg"))); // NOI18N
        jLabel3.setText(" ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 250, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Tela_inicial().setVisible(true);
      dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
